"""Add project fields, manager_id, comments

Revision ID: 88afc74f710d
Revises: f6c8e7c7453f
Create Date: 2026-10-08 14:20:31.767035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88afc74f710d'
down_revision: Union[str, Sequence[str], None] = 'f6c8e7c7453f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('comments', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('ticket_number', sa.String(length=50), nullable=True))
    op.add_column('projects', sa.Column('requester', sa.String(length=150), nullable=True))
    op.add_column('projects', sa.Column('comments', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('manager_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['manager_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'manager_id')
    op.drop_column('projects', 'comments')
    op.drop_column('projects', 'requester')
    op.drop_column('projects', 'ticket_number')
    op.drop_column('activities', 'comments')
    # ### end Alembic commands ###
