"""Add Deliverable model and deliverable_id to Activity

Revision ID: ecc177e2158f
Revises: 88afc74f710d
Create Date: 2026-10-08 15:11:03.008668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecc177e2158f'
down_revision: Union[str, Sequence[str], None] = '88afc74f710d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deliverables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('progress', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deliverables_id'), 'deliverables', ['id'], unique=False)
    op.add_column('activities', sa.Column('deliverable_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_activities_deliverables', 'activities', 'deliverables', ['deliverable_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint('fk_activities_deliverables', 'activities', type_='foreignkey')
    op.drop_column('activities', 'deliverable_id')
    op.drop_index(op.f('ix_deliverables_id'), table_name='deliverables')
    op.drop_table('deliverables')
    # ### end Alembic commands ###
